export const abbrMap: Record<string, string> = {
	"s. m.": "substantivo masculino",
	"s. f.": "substantivo feminino",
	"(ri-ma)": "classe de substantivos singular (ri-), plural (ma-)",
	"(mu-mi)": "classe de substantivos singular (mu-), plural (mi-)",
	"(ri-ti)": "classe de substantivos singular (ri-), plural (ti-)",
	"(yi-ti)": "classe de substantivos singular (yi-), plural (ti-)",
	"(xi-svi)": "classe de substantivos singular (xi-), plural (svi-)",
	"(ma)": "classe de substantivos",
	"pron. p.": "pronome pessoal",
	"pron.p.": "pronome pessoal",
	"pron. ps.": "pronome possessivo",
	"pron. dem.": "pronome demonstrativo",
	"pron.dem.": "pronome demonstrativo",
	"v. t.": "verbo transitivo",
	"v. i.": "verbo intransitivo",
	"v. caus.": "verbo causativo",
	"v. pron.": "verbo pronominal",
	"v. neut. pass.": "verbo neutro passivo",
	"v. pron. rec.": "verbo pronominal recíproco",
	"v. pass.": "voz passiva",
	"v. apl.": "verbo aplicativo",
	"v. aux.": "verbo auxiliar",
	"v. rec.": "verbo recíproco",
	"adj.": "adjetivo",
	"adj. 2 gen.": "adjetivo de dois gêneros",
	"loc. adj.": "locução adjetiva",
	"loc.adv.": "locução adverbial",
	"art. def. f.": "artigo definido feminino",
	"prep.": "preposição",
	"conj.": "conjunção",
	"f.": "feminino",
	"sing.": "singular",
	"pp p.": "pessoa plural",
	"conc.": "concordância",
	"part. gen.": "partícula genitiva",
	"(P)": "aportuguesamento",
	P: "aportuguesamento",
	"adv.": "advérbio",
	"interj.": "interjeição",
	"A.C.": "antes de Cristo",
	"s. 2 gen.": "substantivo de dois gêneros",
	"pl.": "plural",
	"ut.": "usado transitivamente",
	"ext.": "extensão",
};
